---
kind: pipeline
name: testing-amd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - pull_request

steps:
  - name: test-versioned-formulae
    image: homebrew/brew:latest
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    commands:
      - brew tap gitea/gitea "$${PWD}"
      - brew install gitea/gitea/tea
      - tea --version
      - brew install gitea/gitea/gitea
      - gitea --version

  - name: test-head-formulae
    image: homebrew/brew:latest
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    commands:
      - brew tap gitea/gitea "$${PWD}"
      - brew install gitea/gitea/tea-head
      - tea --version
      - brew install gitea/gitea/changelog
      - changelog --version
      - brew install gitea/gitea/gitea-head
      - gitea --version

---
kind: pipeline
name: testing-arm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push
    - pull_request

steps:
  - name: test-versioned-formulae
    image: markkrj/homebrew-arm:latest
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    commands:
      - brew tap gitea/gitea "$${PWD}"
      - brew install gitea/gitea/tea
      - tea --version
      - brew install gitea/gitea/gitea
      - gitea --version

  - name: test-head-formulae
    image: markkrj/homebrew-arm:latest
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    commands:
      - brew tap gitea/gitea "$${PWD}"
      - brew install gitea/gitea/tea-head
      - tea --version
      - brew install gitea/gitea/changelog
      - changelog --version
      - brew install gitea/gitea/gitea-head
      - gitea --version

---
kind: pipeline
name: update_version

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - master
  event:
    - cron
  cron:
    - update_version

steps:
  - name: update
    image: alpine:3.15
    pull: always
    commands:
      - apk add --no-cache curl
      - ./bump_version.sh

  - name: push
    image: appleboy/drone-git-push
    pull: always
    settings:
      author_email: "teabot@gitea.io"
      author_name: GiteaBot
      branch: master
      commit: true
      commit_message: "[skip ci] Updated Version via cron"
      remote: "git@gitea.com:gitea/homebrew-gitea.git"
    environment:
      GIT_PUSH_SSH_KEY:
        from_secret: git_push_ssh_key
