name: test

on:
  - pull_request
  - push

jobs:
  test:
    strategy:
      matrix:
        brew_version: ["3.6.21", "4.1.7", "latest"]
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew:${{ matrix.brew_version }}
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: install node
        # to use actions/checkout
        run: |
          brew install node
          node --version
      - uses: actions/checkout@v3
      - name: test install
        run: |
          brew tap gitea/gitea "${PWD}"
          brew install gitea/gitea/tea
          tea --version
          brew install gitea/gitea/gitea
          gitea --version
          brew install gitea/gitea/act_runner
          act_runner --version
  # TODO: test for arm
  # There is no arm image for homebrew/brew, and the image markkrj/homebrew-arm hasn't been updated for years
